#!/bin/bash
DATE=`date +%Y-%m-%d`

echo "Total req:"
wc -l localhost_access_log.${DATE}.txt | cut -d ' ' -f1
echo ""

echo "OK:"
grep -c '200' localhost_access_log.${DATE}.txt
echo ""

echo "HTTP 500:"
grep -c '500' localhost_access_log.${DATE}.txt
echo ""

echo "req/s:"
cat localhost_access_log.${DATE}.txt | grep 200 | cut -d ' ' -f 4 | uniq -c | awk '{sum+=$1;line+=1} END {print sum/line}'
echo ""
